behaviors:
  Hummingbird:  # Replace with your agent's name
    trainer_type: ppo  # Can also use sac or other RL algorithms if needed
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      gail:  # Adding GAIL for imitation learning
        gamma: 0.99
        strength: 1.0  # Set the strength to 1.0 to rely fully on GAIL
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: "D:\\Mesh_Cutting\\LabEnv\\Assets\\Demonstrations"  # Update this path as needed
    keep_checkpoints: 5
    max_steps: 50000
    time_horizon: 64
    summary_freq: 10000
